# Generated by Django 4.2.9 on 2024-07-25 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_watermeterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1980, message='Тогда мы еще не работали'), django.core.validators.MaxValueValidator(2025, message='Слишком далеко в будущее')], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='watermeterdata',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата показаний'),
        ),
        migrations.AlterField(
            model_name='watermeterdata',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1980, message='Тогда мы еще не работали'), django.core.validators.MaxValueValidator(2025, message='Слишком далеко в будущее')], verbose_name='Год'),
        ),
    ]
